### ISSUE TITLE
 90+ players on server, some widgets still missing onBeginMatch

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion#203]
Looks like we miss to draw some widgets at onBeginMatch for all players (ie $win->show(null) )

It can be linked to the same exact hickup with players at the ticket before this, or gui handler.

Missing widgets are randomly choosen, and they are indeed not drawn in global...
* server info
* maps info
* best cp's at top
* cp times panel

**Comment by oliverde8** [comment]
It probably is an issue with the manialive window manager.  It creates a to big XML,  should split it in multiple executions but the split has maybe an issue

**Comment by reaby** [comment]
Might be also unknown login exception....

**Comment by reaby** [comment]
After debugging at dev server.. I'm quite sure it is the login unknown exception!! 

Gui handler tries to send windows to list of logins.. okay, so gui handler does update every 0.2 seconds.. if player is at the list (while he was at server) but disconnected in 0.2 seconds time.. the list of logins is not synced anymore. 

So. 2 possibilities to fix: 
1) redo list with the players still at server on next loop.
2) send windows individually and see when it fails.. i think the first one is better, since this gets slow.

**Comment by oliverde8** [comment]
The second one is normally already coded. So there is an issue with that.

**Comment by reaby** [comment]
nope... it had bug

**Comment by reaby** [comment]
Reopening this as the problem still exists... 
problem might be still splitting the too big window xml...

**Comment by jaga01** [comment]
On my server- The problem was the massive database migrating from Xaseco that was about over 5000 records on some maps. I cleaned records and ranks tabels from database and everything works perfect. Maybe you can add on database migration tool something like => only first  500-1000 records for every map to be migrated(if is possible ofcorse) to avoid this kind of situations, because Xaseco has unlimited counting even if you set a maximum of records in it`s configuration.

**Comment by jaga01** [comment]
Now is fixed BTW :D sry for bothering so much time, probably you hate me now

**Comment by oliverde8** [comment]
There is still an issue, normally the database size should not affect the data sent to each widget, it should only load from the DB the X records + each 1 for each player worse case. so 500 + 200 = 700. My test had showed the widgets working fine for at least 2K records.

**Comment by reaby** [comment]
Yep, problem seamed to be ranks calculation taking massive 20+ seconds.
I managed to reduce the sql query down to 1.5 seconds, and it looks like the missing panels is also fixed!

**Comment by jaga01** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  iiiieeeeeiiii


Trimis din Yahoo Mail pentru iPhone


La miercuri, iulie 13, 2016, 18:07, reaby <notifications@github.com> a scris:


Closed #203.
